#!/bin/bash

# dependencies ─────────────────────────────────────────────────────────────────

script="$(basename -- "${BASH_SOURCE[0]}")"

# script arguments for escalation

self_arguments=("${@}")

if [ "${frobulator_loaded}" != "true" ]
then
	echo
	echo "[  >  ] Checking..."
	echo

	# root through sudo keeps using the user's frobulator

	if [ -n "${SUDO_USER}" ]
	then
		USER="${SUDO_USER}"
		HOME="$(getent passwd "${SUDO_USER}" | cut -d ':' -f 6)"
	fi

	frobulator="${HOME}/.local/bin/frobulator"
	frobulator_download="$(mktemp)"

	mkdir -p "${HOME}/.local/bin"

	# latest release - curl or wget - local copy replaced only by a newer one

	curl -s -L -o "${frobulator_download}" get.frbltr.app 2> /dev/null ||
	wget -q -O "${frobulator_download}" get.frbltr.app 2> /dev/null

	version_online="$(grep -m 1 '^update=' "${frobulator_download}")"
	version_local="$(grep -m 1 '^update=' "${frobulator}" 2> /dev/null)"

	if [[ "${version_online}" > "${version_local}" ]]
	then
		mv -f "${frobulator_download}" "${frobulator}"

		chmod +x "${frobulator}"
	fi

	rm -f "${frobulator_download}"

	if [ ! -f "${frobulator}" ]
	then
		echo "[  !  ] Unable to fetch frobulator ── [ get.frbltr.app ]"
		echo

		exit 1
	fi

	source "${frobulator}"
fi

# superuser ────────────────────────────────────────────────────────────────────

frobulator.escalate

# script ───────────────────────────────────────────────────────────────────────

frobulator.script

# version ──────────────────────────────────────────────────────────────────────

version="2026-10-04"

# usage ────────────────────────────────────────────────────────────────────────

while (( $# ))
do
	case "${1}"
	in
		-h|--help)
			echo
			echo -e "Usage: ./${script} -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help    Show [h]elp and usage information."
			echo
			echo -e "'${script}'   [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} -h"
			echo
			echo -e "Unknown option: '${script} ${1}':"
			echo -e "Type './${script} -h' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# variables ────────────────────────────────────────────────────────────────────

directory_models="${PWD}"/models
directory_modules="${PWD}"/modules

date_version=$(date +"%m-%d-%Y")

# defaults ─────────────────────────────────────────────────────────────────────

# functions ────────────────────────────────────────────────────────────────────

frobulator.inf "Generating model entries"

frobulator.fwd "Writing..."

# generate header

cat << 'MODEL-DRAWER-HEADER' -> "modules/drawer.html"

			<!-- scripts -->

			<script src="/javascript/year.js" type="text/javascript"></script>

			<script type="text/javascript">

			$(function() {

				$.get("/modules/notice.html", function(data) {

					$("#notice").append(data);

				});

			});

			</script>

			<!-- notice -->

			<div id="notice">

			</div>

			<!-- models start -->

			<div class="grid">

MODEL-DRAWER-HEADER

# generate model entries

# values

list_extensions=(
	png
)

for extension in ${list_extensions[@]}
do
	count_entries=0

	list_renders=( $(find "${directory_models}" -type f -iname "render.${extension}" | sort) )

	# set IFS

	IFS=$'\n'

	for path_render in ${list_renders[@]}
	do
		path_render=$(echo "${path_render}" | cut -d '/' -f6-)

		# get model file name from path

		file_render="${path_render##*/}"

		# strip extension from model file name

		name_render="${file_render%.*}"

		# use model directory as root

		directory_model="${path_render%/*/*}"

		content_compatibility=$(cat "${directory_model}"/compatibility)

		text_compatibility=$(echo ${content_compatibility})

		content_category=$(cat "${directory_model%/*}"/title)

		text_category=$(echo ${content_category})

		content_name=$(cat "${directory_model}"/model)

		text_name=$(echo ${content_name//\<\/\br\>/})

		# model folder name - hidden product name

		name_folder_model="${directory_model##*/}"

		content_title=$(cat "${directory_model}"/title)

		text_title=$(echo ${content_title//\<\/\br\>/})

		content_dart=$(cat "${directory_model}"/dart)

		text_dart=$(echo ${content_dart//\<\/\br\>/})

		content_type=$(cat "${directory_model}"/type)

		text_type=$(echo ${content_type//\<\/\br\>/})

		content_attachment=$(cat "${directory_model}"/attachment)

		text_attachment=$(echo ${content_attachment})

		content_weight=$(cat "${directory_model}"/weight)

		text_weight=$(echo ${content_weight})

		file_paypal="${directory_model}"/paypal

		id_paypal=$(cat "${directory_model}"/paypal)

		file_price="${directory_model}"/price

		price_model=$(cat "${directory_model}"/price)

		file_quote="${directory_model}"/quote

		price_print=$(cat "${directory_model}"/quote)

# generate model drawer entries

cat << MODEL-CONTENT ->> "modules/drawer.html"
				<div class="container product">

					<div class="grid">

						<div class="grid-2 text-left">

							CATEGORY

						</div>

						<div class="grid-2 text-right">

							${text_category}

						</div>

						<div class="grid-2 text-left">

							IDENTIFIER

						</div>

						<div class="product-identifier grid-2 text-right">

							${id_paypal}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-2 text-left">

							MODEL // US$ ${price_model}

						</div>

						<div class="grid-2 text-right">

							<a class="cursor-cell" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=${id_paypal}" target="_blank">

								<label class="cart cursor-pointer text-bold">[ ADD TO CART ]</label>

							</a>

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-2 text-left">

							PRINT // US$ ${price_print}

						</div>

						<div class="grid-2 text-right">


							<label for="modal-quote" class="quote cursor-pointer text-bold">[ QUOTE ]</label>

						</div>

						<div class="grid-4">

							<img src="/${directory_model}/renders/thumbnail/thumbnail.png">

						</div>

						<div class="grid-1">

							COMPATIBILITY

						</div>

						<div class="grid-3 text-right">

							${text_compatibility}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							MODEL

						</div>

						<div class="grid-3 text-right">

							${text_name}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							TITLE

						</div>

						<div class="grid-3 text-right">

							${text_title}

						</div>

						<div class="grid-1">

							DART

						</div>

						<div class="grid-3 text-right">

							${text_dart}

						</div>

						<div class="grid-1">

							TYPE

						</div>

						<div class="grid-3 text-right">

							${text_type}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							ATTACHMENT

						</div>

						<div class="grid-3 text-right">

							${text_attachment}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							WEIGHT

						</div>

						<div class="grid-3 text-right">

							${text_weight} G

						</div>

						<div class="hide product-name grid-4 text-right">

							${name_folder_model}

						</div>

					</div>

				</div>

MODEL-CONTENT

	(( count_entries ++ ))

	done

cat << COPYRIGHT ->> "modules/drawer.html"
				<!-- copyright -->

				<div class="container copyright text-center">

					<div class="grid">

						<div class="grid-4 text-right">

							COPYRIGHT

						</div>

						<div class="grid-4">

							<a class="container copyright" href="https://nathaneltitane.com">

								<img src="/avatar/avatar-bird.png">

							</a>

						</div>

						<div class="grid-4">

							PEW! PEW! PRINTS

						</div>

						<div class="grid-4">

							[ FOAM BLASTER PRINTED PARTS + MODS ]

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-4">

							PEW! PEW!

						</div>

						<div class="grid-4">

							[ VERSION // ${date_version} ]

						</div>

						<div class="grid-4">

							ALL RIGHTS RESERVED

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-4">

							N Λ T H Λ N E L - © <text id="year"></text>

						</div>

					</div>

COPYRIGHT

cat << MODEL-CONTENT ->> "modules/drawer.html"
				</div>

				<!-- models end -->
MODEL-CONTENT

done

frobulator.inf "Parsed model entries" "[ ${count_entries} ]"

frobulator.cpt "Complete" "[ Drawer ]"


