#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

USER_HOME="${HOME}"

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="12-24-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "modules/models.html"

			<!-- models -->

MODEL-DRAWER-HEADER

# generate model entries

# values

extensions_list=(
	png
)

for extension in ${extensions_list[@]}
do
	count=1

	# shuffle models directories list:
	# generates sorted showcase of all models on each update

	for models_list in $(find models/ -type f -iname render."${extension}" | sort)
	do
		IFS='/' read -r -a path <<< $(echo "$models_list")

		# /models/model-type/model/renders/render-type/render.${extension}

		# "${path[0]}" /models
		# "${path[1]}" /model-category
		# "${path[2]}" /model
		# "${path[3]}" /renders

		# render types:

		# "${path[4]}" /thumbnail

		# "${path[5]}" /render.extension

		model_category=$(cat ${path[0]}/${path[1]}/title)

		model_title=$(cat ${path[0]}/${path[1]}/${path[2]}/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal=${path[0]}/${path[1]}/${path[2]}/paypal

		model_paypal_id=$(cat ${path[0]}/${path[1]}/${path[2]}/paypal)

		model_price=${path[0]}/${path[1]}/${path[2]}/price

		model_paypal_price=$(cat ${path[0]}/${path[1]}/${path[2]}/price)

# generate model drawer entries

cat << MODEL-CONTENT ->> "modules/models.html"
			<div class="section">

				<hr>

			</div>

			<div class="section text-center">

				<div class="grid grid-column grid-center grid-between">

					<div class="grid-cell">

						<h3>${title}</h3>

					</div>

					<div class="grid-cell">

						<div class="container image">

							<img src="/${path[0]}/${path[1]}/${path[2]}/renders/render.png" />

						</div>

					</div>

					<div class="grid grid-row">

						<div class="grid-cell">

							<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=${model_paypal_id}">

							BLACK PRINT</br>

							\$${model_paypal_price}
							</a>

						</div>

					</div>

				</div>

			</div>

MODEL-CONTENT

	((count++))

	done
done

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "Models" "[ Done ]"
echo
