#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="2022-01-04"

# usage ////////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

local_content_directory="${PWD}"/
local_server_directory=/var/www/html/pewpewprints/

# defaults /////////////////////////////////////////////////////////////////////

list=(
	apache2
)

frobulator.require ${list[@]}

# functions ////////////////////////////////////////////////////////////////////

# generate server configuration

cat <<- 'FILE' > /etc/apache2/sites-enabled/pewpewprints.conf
<VirtualHost *: 80>
        ServerAdmin     nathanel.titane@gmail.com
        ServerName      pewpewprints
        ServerAlias     dev.pewpewprints.com
        DocumentRoot    /var/www/html/pewpewprints/
        ErrorLog        ${APACHE_LOG_DIR}/pewpewprints.error.log
        CustomLog       ${APACHE_LOG_DIR}/pewpewprints.access.log combined
</VirtualHost>
FILE

# reload service

service apache2 reload

# enable virtual host configuration distribution

a2ensite pewpewprints.conf

# configure server host address

cat <<- 'FILE' >> /etc/hosts
127.0.0.1       dev.pewpewprints.com
FILE

# generate local server directory

directories_list=(
	/var/www/html/pewpewprints
)

for directory in ${directories_list[@]}
do
	mkdir -p "${directory}"

	chmod -R 777 "${directory}"
done

# pull /////////////////////////////////////////////////////////////////////////

rsync							\
	--archive					\
	--quiet						\
	--recursive					\
	--exclude='*.sldasm'		\
	--exclude='*.sldprt'		\
	--exclude='*.stl'			\
								"${local_content_directory}"/* "${local_server_directory}"

frobulator.cpt "Complete" "[ Server ]"
echo
