#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	export self_arguments="${@}"
fi

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2023-02-09"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

models_directory="${PWD}"/models
modules_directory="${PWD}"/modules

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << 'MODEL-DRAWER-HEADER' -> "modules/drawer.html"

			<!-- scripts -->

			<script src="/javascript/year.js" type="text/javascript"></script>

			<script type="text/javascript">

			$(function() {

				$.get("/modules/notice.html", function(data) {

					$("#notice").append(data);

				});

			});

			</script>

			<!-- notice -->

			<div id="notice">

			</div>

			<!-- models start -->

			<div class="grid">

MODEL-DRAWER-HEADER

# generate model entries

# values

extensions_list=(
	png
)

for extension in ${extensions_list[@]}
do
	count=1

	models_list=( $(find "${models_directory}" -type f -iname "render.${extension}" | sort) )

	# set IFS

	IFS=$'\n'

	for model_path in ${models_list[@]}
	do
		model_path=$(echo "${model_path}" | cut -d '/' -f6-)

		# get model file name from path

		model_file="${model_path##*/}"

		# strip extension from model file name

		model_name="${model_file%.*}"

		# use model directory as root

		model_directory="${model_path%/*/*}"

		model_compatibility=$(cat "${model_directory}"/compatibility)

		model_compatibility_string=$(echo ${model_compatibility})

		model_title=$(cat "${model_directory}"/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_dart=$(cat "${model_directory}"/dart)

		model_dart_string=$(echo ${model_dart//\<\/\br\>/})

		model_type=$(cat "${model_directory}"/type)

		model_type_string=$(echo ${model_type//\<\/\br\>/})

		model_attachment=$(cat "${model_directory}"/attachment)

		model_attachment_string=$(echo ${model_attachment})

		model_weight=$(cat "${model_directory}"/weight)

		model_weight_string=$(echo ${model_weight})

		model_paypal="${model_directory}"/paypal

		model_paypal_id=$(cat "${model_directory}"/paypal)

		model_price="${model_directory}"/price

		model_paypal_price=$(cat "${model_directory}"/price)

		model_quote="${model_directory}"/quote

		model_quote_price=$(cat "${model_directory}"/quote)

# generate model drawer entries

cat << MODEL-CONTENT ->> "modules/drawer.html"
				<div class="container product">

					<div class="grid">

						<div class="grid-2 text-left">

							CATEGORY

						</div>

						<div class="grid-2 text-right">

							${model_category}

						</div>

						<div class="grid-2 text-left">

							IDENTIFIER

						</div>

						<div class="product-identifier grid-2 text-right">

							${model_paypal_id}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-2 text-left">

							MODEL // US$ ${model_paypal_price}

						</div>

						<div class="grid-2 text-right">

							<a class="cursor-cell" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=${model_paypal_id}" target="_blank">

								<label class="cart cursor-pointer text-bold">[ ADD TO CART ]</label>

							</a>

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-2 text-left">

							PRINT // US$ ${model_quote_price}

						</div>

						<div class="grid-2 text-right">


							<label for="modal-quote" class="quote cursor-pointer text-bold">[ QUOTE ]</label>

						</div>

						<div class="grid-4">

							<img src="/${model_directory}/renders/thumbnail/thumbnail.png">

						</div>

						<div class="grid-1">

							COMPATIBILITY

						</div>

						<div class="grid-3 text-right">

							${model_compatibility_string}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							MODEL

						</div>

						<div class="grid-3 text-right">

							${model_name_string}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							TITLE

						</div>

						<div class="grid-3 text-right">

							${model_title_string}

						</div>

						<div class="grid-1">

							DART

						</div>

						<div class="grid-3 text-right">

							${model_dart_string}

						</div>

						<div class="grid-1">

							TYPE

						</div>

						<div class="grid-3 text-right">

							${model_type_string}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							ATTACHMENT

						</div>

						<div class="grid-3 text-right">

							${model_attachment_string}

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-1">

							WEIGHT

						</div>

						<div class="grid-3 text-right">

							${model_weight_string} G

						</div>

						<div class="hide product-name grid-4 text-right">

							${path[2]}

						</div>

					</div>

				</div>

MODEL-CONTENT

	((count++))

	done

cat << COPYRIGHT ->> "modules/drawer.html"
				<!-- copyright -->

				<div class="container copyright text-center">

					<div class="grid">

						<div class="grid-4 text-right">

							COPYRIGHT

						</div>

						<div class="grid-4">

							<a class="container copyright" href="https://nathaneltitane.com">

								<img src="/avatar/avatar-bird.png">

							</a>

						</div>

						<div class="grid-4">

							PEW! PEW! PRINTS

						</div>

						<div class="grid-4">

							[ FOAM BLASTER PRINTED PARTS + MODS ]

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-4">

							PEW! PEW!

						</div>

						<div class="grid-4">

							[ VERSION // ${stamp} ]

						</div>

						<div class="grid-4">

							ALL RIGHTS RESERVED

						</div>

						<div class="grid-4 section">

							<hr>

						</div>

						<div class="grid-4">

							N Λ T H Λ N E L - © <text id="year"></text>

						</div>

					</div>

COPYRIGHT

cat << MODEL-CONTENT ->> "modules/drawer.html"
				</div>

				<!-- models end -->
MODEL-CONTENT

done

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.cpt "Complete" "[ Drawer ]"
echo


