#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

USER_HOME="${HOME}"

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="12-24-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "modules/models.html"

			<!-- models -->

			<div class="grid grid-around grid-center grid-wrap">

MODEL-DRAWER-HEADER

# generate model entries

# values

extensions_list=(
	png
)

for extension in ${extensions_list[@]}
do
	count=1

	# shuffle models directories list:
	# generates sorted showcase of all models on each update

	for models_list in $(find models/ -type f -iname render."${extension}" | sort)
	do
		IFS='/' read -r -a path <<< $(echo "$models_list")

		# /models/model-type/model/renders/render-type/render.${extension}

		# "${path[0]}" /models
		# "${path[1]}" /model-category
		# "${path[2]}" /model
		# "${path[3]}" /renders

		# render types:

		# "${path[4]}" /thumbnail

		# "${path[5]}" /render.extension

		model_category=$(cat ${path[0]}/${path[1]}/title)

		model_compatibility=$(cat ${path[0]}/${path[1]}/${path[2]}/compatibility)

		model_compatibility_string=$(echo ${model_compatibility//\<\/\br\>/})

		model_title=$(cat ${path[0]}/${path[1]}/${path[2]}/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal=${path[0]}/${path[1]}/${path[2]}/paypal

		model_paypal_id=$(cat ${path[0]}/${path[1]}/${path[2]}/paypal)

		model_price=${path[0]}/${path[1]}/${path[2]}/price

		model_paypal_price=$(cat ${path[0]}/${path[1]}/${path[2]}/price)



# generate model drawer entries

cat << MODEL-CONTENT ->> "modules/models.html"
				<div class="grid grid-responsive grid-column">

					<div class="container">

						<div class="grid grid-center">

							<div class="image">

								<a href="/${path[0]}/${path[1]}/${path[2]}/renders/render.png" target="_blank">

									<img src="/${path[0]}/${path[1]}/${path[2]}/renders/thumbnail/thumbnail.png">

								</a>

							</div>

						</div>

						<div class="container">

							<div class="grid-cell text-center">

								COMPATIBILITY<br>

								${model_compatibility_string}

							</div>

							<div class="grid-cell section text-center">

								<hr>

							</div>

							<div class="grid-cell text-center">

								${model_title}

							</div>

						</div>

					</div>

					<div class="container cursor-crosshair">

						<div class="grid-cell text-center cursor-crosshair">

							<a class="cursor-crosshair" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=${model_paypal_id}" target="_blank">

							\$${model_paypal_price} USD // ADD TO CART</br>

							</a>

						</div>

					</div>

				</div>

MODEL-CONTENT



	((count++))

	done

	cat << MODEL-CONTENT ->> "modules/models.html"
			</div>

MODEL-CONTENT
done

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "Models" "[ Done ]"
echo
