#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-14-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

local_directory=/media/internal/Printer/models/pewpewprints
local_models_directory="${local_directory}"

server_directory="${PWD}"
server_models_directory="${server_directory}"/models

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# prepare update

if [[ -d "${server_models_directory}" ]]
then
	frobulator.delete "${server_directory}" models
fi

# pull /////////////////////////////////////////////////////////////////////////

rsync								\
	--archive						\
	--quiet							\
	--recursive						\
	--exclude='*.FCStd'				\
	--exclude='*.FCBak'				\
	--exclude='*.sldasm'			\
	--exclude='*.sldprt'			\
	--exclude='*.stl'				\
	--exclude="base"				\
	--exclude="comission"			\
	--exclude="custom"				\
	--exclude="part"				\
	--exclude="work-in-progress"	\
									"${local_models_directory}"/* "${server_models_directory}"

frobulator.scs "Copy" "[ Done ]"
echo
